CREATE TABLE IF NOT EXISTS EQUIPO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_SERIE VARCHAR(255),
    DESCRIPCION VARCHAR(255),
    NOMBRE VARCHAR(255),
    FECHA_COMPRA DATE,
    VALOR_COMPRA DOUBLE
);
